dialogo :: Int -> Int -> Int -> Int -> (String, String)
dialogo h1 m1 h2 m2 = if (h1 > 24 || h2 > 24 || m1 > 59 || m2 > 59)
                       then error "Invalido"
                       else if (convert == 1)
                        then ("Passou apenas " ++ show (convert) ++ " minuto!", "De facto!")
                        else if (convert < 60)
                         then ("Passaram apenas " ++ show (convert) ++ " minutos!", "De facto!")
                         else if (horas /= 1 && minutos == 0)
                          then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " horas?!")
                          else if (horas == 1 && minutos == 0)
                           then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " hora?!")
                           else if (horas /= 1 && (horas-1) /= 1 && minutos /= 1 && m1 > m2)
                            then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas-1) ++ " horas e " ++ show (minutos) ++ " minutos?!")
                            else if (horas /= 1 && minutos /= 1)
                             then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " horas e " ++ show (minutos) ++ " minutos?!")
                             else if (horas == 1 && minutos /= 1)
                              then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " hora e " ++ show (minutos) ++ " minutos?!")
                              else if (horas /= 1 && minutos == 1)
                               then ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " horas e " ++ show (minutos) ++ " minuto?!")
                               else ("Passaram apenas " ++ show (convert) ++ " minutos!", "Queres dizer, " ++ show (horas) ++ " hora e " ++ show (minutos) ++ " minuto?!")
                where
                  convert = abs (((h1*60) + m1) - ((h2*60) + m2))
                  horas   = abs ((h1 + (div m1 60)) - (h2 + (div m2 60)))
                  minutos = mod convert 60
